resource.AddFile("materials/steamlogo.png")
resource.AddFile("materials/youtubelogo.png")
resource.AddFile("materials/discordlogo.png")
resource.AddFile("materials/checklogo.png")
resource.AddFile("materials/crosslogo.png")
resource.AddFile("materials/giftlogo.png")
resource.AddFile("materials/giftviplogo.png")
resource.AddFile("materials/timerlogo.png")
resource.AddFile("materials/clocklogo.png")
resource.AddFile("materials/settingslogo.png")
resource.AddFile("materials/reflogo.png")
resource.AddFile("materials/moneylogo.png")
resource.AddFile("materials/giftcardlogo.png")
resource.AddFile("materials/coinlogo.png")
include('rewards/init.lua')

