resource.AddFile("materials/steamlogo.png")
resource.AddFile("materials/discordlogo.png")
resource.AddFile("materials/checklogo.png")
resource.AddFile("materials/giftlogo.png")
resource.AddFile("materials/giftviplogo.png")
resource.AddFile("materials/timerlogo.png")
resource.AddFile("materials/settingslogo.png")
resource.AddFile("materials/reflogo.png")
resource.AddFile("materials/moneylogo.png")
resource.AddFile("materials/giftcardlogo.png")
resource.AddFile("materials/coinlogo.png")
include('RewardsPlus/rewardsplus_init.lua')

